create table
  public.locations (
    id bigint generated by default as identity,
    bs smallint not null,
    created_at timestamp with time zone not null,
    lat double precision not null,
    lon double precision not null,
    topic text not null,
    tst timestamp with time zone not null,
    acc smallint null,
    alt smallint null,
    batt smallint null,
    BSSID text null,
    cog smallint null,
    conn text null,
    inregions text[] null,
    inrids text[] null,
    m smallint null,
    p double precision null,
    poi text null,
    rad smallint null,
    SSID text null,
    t text null,
    tag text null,
    tid text null,
    vac smallint null,
    vel smallint null,
    constraint locations_pkey primary key (id)
  ) tablespace pg_default;

CREATE POLICY "Enable insert for anon users only" ON "public"."locations"
AS PERMISSIVE FOR INSERT
TO anon

WITH CHECK (true)
