create table
  public.logs (
    id bigint generated by default as identity,
    created_at timestamp with time zone null default now(),
    log text not null,
    constraint logs_pkey primary key (id)
  ) tablespace pg_default;

CREATE POLICY "Enable insert for anon users only" ON "public"."logs"
AS PERMISSIVE FOR INSERT
TO anon

WITH CHECK (true)
