create table
	public.messages (
		"id" bigint generated by default as identity,
		"created_at" timestamp with time zone null default now(),
		"message" text not null,
		constraint messages_pkey primary key (id)
	) tablespace pg_default;

CREATE POLICY "Enable insert for anon users only" ON "public"."messages"
AS PERMISSIVE FOR INSERT
TO anon

WITH CHECK (true)
